sonar.projectKey=aci-collector
sonar.projectName=
sonar.projectVersion=
sonar.sources=.
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.python.coverage.reportPaths=./actions/review/aiops/scripts/coverage.xml
sonar.python.version=3.12
sonar.exclusions=**/test/**/*,**/test/*,jest.config.js
